name: C CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  formatting-check:
    name: Stylecheck
    runs-on: ubuntu-latest
    steps:
      # 1. Clone repository
      - name: Clone
        uses: actions/checkout@v4

      # 2. Install clang-format
      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '14'
          check-path: 'mlx-codefree-communication'

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      # 1. Clone repository
      - name: Clone
        uses: actions/checkout@v4

      # 2. Install Ceedling to run tests (using ruby)
      - name: Install Ceedling
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby
          sudo gem install ceedling

      # 3. Run tests
      - name: Run Unit Tests
        run: ceedling test:all

  generate-docs:
    name: Documentation
    runs-on: ubuntu-latest
    # Only deploy the website when code is merged/pushed directly to main, 
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [formatting-check, unit-tests] 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Clone repository
      - name: Clone
        uses: actions/checkout@v4

      # 2. Install necessary packages
      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # 3. Generate doxy output
      - name: Run Doxygen
        run: doxygen Doxyfile

      # 4. nojekyll file for dir name compatibility
      - name: Add .nojekyll file
        run: touch html/.nojekyll

      # 5. Setup page
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      # 6. Upload generated doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './html'

      # 7. Deploy output
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4